# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MGCarouselView-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod  'iCarousel'

  # Pods for MGCarouselView-Demo

  target 'MGCarouselView-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MGCarouselView-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
